package net.cmr.jurassicrevived.item;

import dev.architectury.registry.CreativeTabRegistry;
import dev.architectury.registry.registries.DeferredRegister;
import dev.architectury.registry.registries.RegistrySupplier;
import net.cmr.jurassicrevived.Constants;
import net.cmr.jurassicrevived.block.ModBlocks;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;

public class ModCreativeTabs {
	public static final DeferredRegister<CreativeModeTab> TABS =
		DeferredRegister.create(Constants.MOD_ID, Registries.CREATIVE_MODE_TAB);

	public static final RegistrySupplier<CreativeModeTab> ITEM_TAB = TABS.register("item_tab",
		() -> CreativeTabRegistry.create(builder -> {
			builder.title(Component.translatable("itemGroup." + Constants.MOD_ID + ".item_tab"));
			builder.icon(() -> new ItemStack(ModItems.MOSQUITO_IN_AMBER.get()));
			builder.displayItems((params, output) -> {
				output.accept(ModItems.FROG_MATERIAL.get());
				output.accept(ModItems.FROG_DNA.get());
				output.accept(ModItems.TEST_TUBE.get());
				output.accept(ModItems.SYRINGE.get());
				output.accept(ModItems.CRUSHED_FOSSIL.get());
				output.accept(ModItems.MOSQUITO_IN_AMBER.get());
				output.accept(ModItems.FROZEN_LEECH.get());
				output.accept(ModItems.FROZEN_BONE.get());
				output.accept(ModItems.CABLE.get());
				output.accept(ModItems.SCREEN.get());
				output.accept(ModItems.PROCESSOR.get());
				output.accept(ModItems.TIRE.get());
				output.accept(ModItems.CUTTING_BLADES.get());
				output.accept(ModItems.WRENCH.get());
				output.accept(ModItems.MAC_N_CHEESE.get());
				output.accept(ModItems.WALNUT_PUMPKIN_PIE.get());
				output.accept(ModItems.BANANA_NUT_COOKIE.get());
			});
		}));
	
	public static final RegistrySupplier<CreativeModeTab> BLOCK_TAB = TABS.register("block_tab",
		() -> CreativeTabRegistry.create(builder -> {
			builder.title(Component.translatable("itemGroup." + Constants.MOD_ID + ".block_tab"));
			builder.icon(() -> new ItemStack(ModBlocks.GYPSUM_STONE_BRICKS.get()));
			builder.displayItems((params, output) -> {
				output.accept(ModBlocks.CAT_PLUSHIE.get());
				output.accept(ModBlocks.TRASH_CAN.get());
				output.accept(ModBlocks.BENCH.get());
				output.accept(ModBlocks.CHARRED_TERRACOTTA.get());
				output.accept(ModBlocks.FENCE_LIGHT.get());
				output.accept(ModBlocks.LIGHT_POST.get());
				output.accept(ModBlocks.GYPSUM_STONE.get());
				output.accept(ModBlocks.GYPSUM_COBBLESTONE.get());
				output.accept(ModBlocks.GYPSUM_STONE_BRICKS.get());
				output.accept(ModBlocks.SMOOTH_GYPSUM_STONE.get());
				output.accept(ModBlocks.CHISELED_GYPSUM_STONE.get());
				output.accept(ModBlocks.GYPSUM_BRICK_STAIRS.get());
				output.accept(ModBlocks.GYPSUM_BRICK_SLAB.get());
				output.accept(ModBlocks.GYPSUM_BRICK_WALL.get());

				output.accept(ModBlocks.REINFORCED_STONE.get());
				output.accept(ModBlocks.REINFORCED_STONE_BRICKS.get());
				output.accept(ModBlocks.CHISELED_REINFORCED_STONE.get());
				output.accept(ModBlocks.REINFORCED_BRICK_STAIRS.get());
				output.accept(ModBlocks.REINFORCED_BRICK_SLAB.get());
				output.accept(ModBlocks.REINFORCED_BRICK_WALL.get());

				output.accept(ModBlocks.LOW_SECURITY_FENCE_POLE.get());
				output.accept(ModBlocks.LOW_SECURITY_FENCE_WIRE.get());
				output.accept(ModBlocks.MEDIUM_SECURITY_FENCE_POLE.get());
				output.accept(ModBlocks.MEDIUM_SECURITY_FENCE_WIRE.get());

				output.accept(ModBlocks.ITEM_PIPE.get());
				output.accept(ModBlocks.FLUID_PIPE.get());
				output.accept(ModBlocks.POWER_PIPE.get());

				output.accept(ModBlocks.TANK.get());
				output.accept(ModBlocks.POWER_CELL.get());
				output.accept(ModBlocks.WOOD_CRATE.get());
				output.accept(ModBlocks.IRON_CRATE.get());

				output.accept(ModBlocks.GENERATOR.get());
				output.accept(ModBlocks.DNA_EXTRACTOR.get());
				output.accept(ModBlocks.DNA_ANALYZER.get());
				output.accept(ModBlocks.FOSSIL_GRINDER.get());
				output.accept(ModBlocks.FOSSIL_CLEANER.get());
				output.accept(ModBlocks.DNA_HYBRIDIZER.get());
				output.accept(ModBlocks.EMBRYONIC_MACHINE.get());
				output.accept(ModBlocks.EMBRYO_CALCIFICATION_MACHINE.get());
				output.accept(ModBlocks.INCUBATOR.get());

				output.accept(ModBlocks.WHITE_GENERATOR.get());
				output.accept(ModBlocks.WHITE_DNA_EXTRACTOR.get());
				output.accept(ModBlocks.WHITE_DNA_ANALYZER.get());
				output.accept(ModBlocks.WHITE_FOSSIL_GRINDER.get());
				output.accept(ModBlocks.WHITE_FOSSIL_CLEANER.get());
				output.accept(ModBlocks.WHITE_DNA_HYBRIDIZER.get());
				output.accept(ModBlocks.WHITE_EMBRYONIC_MACHINE.get());
				output.accept(ModBlocks.WHITE_EMBRYO_CALCIFICATION_MACHINE.get());
				output.accept(ModBlocks.WHITE_INCUBATOR.get());

				output.accept(ModBlocks.STONE_FOSSIL.get());
				output.accept(ModBlocks.DEEPSLATE_FOSSIL.get());
				output.accept(ModBlocks.AMBER_ORE.get());
				output.accept(ModBlocks.DEEPSLATE_ICE_SHARD_ORE.get());
				output.accept(ModBlocks.PERMAFROST.get());
			});
		}));

	public static final RegistrySupplier<CreativeModeTab> PLANT_TAB = TABS.register("plant_tab",
		() -> CreativeTabRegistry.create(builder -> {
			builder.title(Component.translatable("itemGroup." + Constants.MOD_ID + ".plant_tab"));
			builder.icon(() -> new ItemStack(ModBlocks.ROYAL_FERN.get().asItem()));
			builder.displayItems((params, output) -> {
				output.accept(ModBlocks.ROYAL_FERN.get().asItem());
				output.accept(ModBlocks.HORSETAIL_FERN.get().asItem());
				output.accept(ModBlocks.WESTERN_SWORD_FERN.get().asItem());
				output.accept(ModBlocks.ONYCHIOPSIS.get().asItem());
			});
		}));

	public static final RegistrySupplier<CreativeModeTab> DNA_TAB = TABS.register("dna_tab",
		() -> CreativeTabRegistry.create(builder -> {
			builder.title(Component.translatable("itemGroup." + Constants.MOD_ID + ".dna_tab"));
			builder.icon(() -> new ItemStack(ModItems.TYRANNOSAURUS_REX_DNA.get().asItem()));
			builder.displayItems((params, output) -> {
				// Skull fossils (alphabetical)
				output.accept(ModItems.ACHILLOBATOR_SKULL_FOSSIL.get());
				output.accept(ModItems.ALBERTOSAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.ALLOSAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.ALVAREZSAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.ANKYLOSAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.APATOSAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.ARAMBOURGIANIA_SKULL_FOSSIL.get());
				output.accept(ModItems.BARYONYX_SKULL_FOSSIL.get());
				output.accept(ModItems.BRACHIOSAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.CARCHARODONTOSAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.CARNOTAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.CEARADACTYLUS_SKULL_FOSSIL.get());
				output.accept(ModItems.CERATOSAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.CHASMOSAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.CHILESAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.COELOPHYSIS_SKULL_FOSSIL.get());
				output.accept(ModItems.COELURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.COMPSOGNATHUS_SKULL_FOSSIL.get());
				output.accept(ModItems.CONCAVENATOR_SKULL_FOSSIL.get());
				output.accept(ModItems.CORYTHOSAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.DEINONYCHUS_SKULL_FOSSIL.get());
				output.accept(ModItems.DILOPHOSAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.DIMORPHODON_SKULL_FOSSIL.get());
				output.accept(ModItems.DIPLODOCUS_SKULL_FOSSIL.get());
				output.accept(ModItems.DRYOSAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.EDMONTOSAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.GALLIMIMUS_SKULL_FOSSIL.get());
				output.accept(ModItems.GEOSTERNBERGIA_SKULL_FOSSIL.get());
				output.accept(ModItems.GIGANOTOSAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.GUANLONG_SKULL_FOSSIL.get());
				output.accept(ModItems.GUIDRACO_SKULL_FOSSIL.get());
				output.accept(ModItems.HADROSAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.HERRERASAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.HYPSILOPHODON_SKULL_FOSSIL.get());
				output.accept(ModItems.INOSTRANCEVIA_SKULL_FOSSIL.get());
				output.accept(ModItems.LAMBEOSAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.LUDODACTYLUS_SKULL_FOSSIL.get());
				output.accept(ModItems.MAJUNGASAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.MAMENCHISAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.METRIACANTHOSAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.MOGANOPTERUS_SKULL_FOSSIL.get());
				output.accept(ModItems.MUSSASAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.NYCTOSAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.ORNITHOLESTES_SKULL_FOSSIL.get());
				output.accept(ModItems.ORNITHOMIMUS_SKULL_FOSSIL.get());
				output.accept(ModItems.OURANOSAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.OVIRAPTOR_SKULL_FOSSIL.get());
				output.accept(ModItems.PACHYCEPHALOSAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.PARASAUROLOPHUS_SKULL_FOSSIL.get());
				output.accept(ModItems.PROCERATOSAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.PROCOMPSOGNATHUS_SKULL_FOSSIL.get());
				output.accept(ModItems.PROTOCERATOPS_SKULL_FOSSIL.get());
				output.accept(ModItems.PTERANODON_SKULL_FOSSIL.get());
				output.accept(ModItems.PTERODAUSTRO_SKULL_FOSSIL.get());
				output.accept(ModItems.QUETZALCOATLUS_SKULL_FOSSIL.get());
				output.accept(ModItems.RAJASAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.RUGOPS_SKULL_FOSSIL.get());
				output.accept(ModItems.SEGISAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.SHANTUNGOSAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.SPINOSAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.STEGOSAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.STYRACOSAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.SUCHOMIMUS_SKULL_FOSSIL.get());
				output.accept(ModItems.TAPEJARA_SKULL_FOSSIL.get());
				output.accept(ModItems.THERIZINOSAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.THESCELOSAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.TITANOSAURUS_SKULL_FOSSIL.get());
				output.accept(ModItems.TRICERATOPS_SKULL_FOSSIL.get());
				output.accept(ModItems.TROODON_SKULL_FOSSIL.get());
				output.accept(ModItems.TROPEOGNATHUS_SKULL_FOSSIL.get());
				output.accept(ModItems.TUPUXUARA_SKULL_FOSSIL.get());
				output.accept(ModItems.TYRANNOSAURUS_REX_SKULL_FOSSIL.get());
				output.accept(ModItems.UTAHRAPTOR_SKULL_FOSSIL.get());
				output.accept(ModItems.VELOCIRAPTOR_SKULL_FOSSIL.get());
				output.accept(ModItems.ZHENYUANOPTERUS_SKULL_FOSSIL.get());

// Fresh skulls (alphabetical)
				output.accept(ModItems.FRESH_ACHILLOBATOR_SKULL.get());
				output.accept(ModItems.FRESH_ALBERTOSAURUS_SKULL.get());
				output.accept(ModItems.FRESH_ALLOSAURUS_SKULL.get());
				output.accept(ModItems.FRESH_ALVAREZSAURUS_SKULL.get());
				output.accept(ModItems.FRESH_ANKYLOSAURUS_SKULL.get());
				output.accept(ModItems.FRESH_APATOSAURUS_SKULL.get());
				output.accept(ModItems.FRESH_ARAMBOURGIANIA_SKULL.get());
				output.accept(ModItems.FRESH_BARYONYX_SKULL.get());
				output.accept(ModItems.FRESH_BRACHIOSAURUS_SKULL.get());
				output.accept(ModItems.FRESH_CARCHARODONTOSAURUS_SKULL.get());
				output.accept(ModItems.FRESH_CARNOTAURUS_SKULL.get());
				output.accept(ModItems.FRESH_CEARADACTYLUS_SKULL.get());
				output.accept(ModItems.FRESH_CERATOSAURUS_SKULL.get());
				output.accept(ModItems.FRESH_CHASMOSAURUS_SKULL.get());
				output.accept(ModItems.FRESH_CHILESAURUS_SKULL.get());
				output.accept(ModItems.FRESH_COELOPHYSIS_SKULL.get());
				output.accept(ModItems.FRESH_COELURUS_SKULL.get());
				output.accept(ModItems.FRESH_COMPSOGNATHUS_SKULL.get());
				output.accept(ModItems.FRESH_CONCAVENATOR_SKULL.get());
				output.accept(ModItems.FRESH_CORYTHOSAURUS_SKULL.get());
				output.accept(ModItems.FRESH_DEINONYCHUS_SKULL.get());
				output.accept(ModItems.FRESH_DILOPHOSAURUS_SKULL.get());
				output.accept(ModItems.FRESH_DIMORPHODON_SKULL.get());
				output.accept(ModItems.FRESH_DIPLODOCUS_SKULL.get());
				output.accept(ModItems.FRESH_DISTORTUS_REX_SKULL.get());
				output.accept(ModItems.FRESH_DRYOSAURUS_SKULL.get());
				output.accept(ModItems.FRESH_EDMONTOSAURUS_SKULL.get());
				output.accept(ModItems.FRESH_GALLIMIMUS_SKULL.get());
				output.accept(ModItems.FRESH_GEOSTERNBERGIA_SKULL.get());
				output.accept(ModItems.FRESH_GIGANOTOSAURUS_SKULL.get());
				output.accept(ModItems.FRESH_GUANLONG_SKULL.get());
				output.accept(ModItems.FRESH_GUIDRACO_SKULL.get());
				output.accept(ModItems.FRESH_HADROSAURUS_SKULL.get());
				output.accept(ModItems.FRESH_HERRERASAURUS_SKULL.get());
				output.accept(ModItems.FRESH_HYPSILOPHODON_SKULL.get());
				output.accept(ModItems.FRESH_INDOMINUS_REX_SKULL.get());
				output.accept(ModItems.FRESH_INDORAPTOR_SKULL.get());
				output.accept(ModItems.FRESH_INOSTRANCEVIA_SKULL.get());
				output.accept(ModItems.FRESH_LAMBEOSAURUS_SKULL.get());
				output.accept(ModItems.FRESH_LUDODACTYLUS_SKULL.get());
				output.accept(ModItems.FRESH_MAJUNGASAURUS_SKULL.get());
				output.accept(ModItems.FRESH_MAMENCHISAURUS_SKULL.get());
				output.accept(ModItems.FRESH_METRIACANTHOSAURUS_SKULL.get());
				output.accept(ModItems.FRESH_MOGANOPTERUS_SKULL.get());
				output.accept(ModItems.FRESH_MUSSASAURUS_SKULL.get());
				output.accept(ModItems.FRESH_NYCTOSAURUS_SKULL.get());
				output.accept(ModItems.FRESH_ORNITHOLESTES_SKULL.get());
				output.accept(ModItems.FRESH_ORNITHOMIMUS_SKULL.get());
				output.accept(ModItems.FRESH_OURANOSAURUS_SKULL.get());
				output.accept(ModItems.FRESH_OVIRAPTOR_SKULL.get());
				output.accept(ModItems.FRESH_PACHYCEPHALOSAURUS_SKULL.get());
				output.accept(ModItems.FRESH_PARASAUROLOPHUS_SKULL.get());
				output.accept(ModItems.FRESH_PROCERATOSAURUS_SKULL.get());
				output.accept(ModItems.FRESH_PROCOMPSOGNATHUS_SKULL.get());
				output.accept(ModItems.FRESH_PROTOCERATOPS_SKULL.get());
				output.accept(ModItems.FRESH_PTERANODON_SKULL.get());
				output.accept(ModItems.FRESH_PTERODAUSTRO_SKULL.get());
				output.accept(ModItems.FRESH_QUETZALCOATLUS_SKULL.get());
				output.accept(ModItems.FRESH_RAJASAURUS_SKULL.get());
				output.accept(ModItems.FRESH_RUGOPS_SKULL.get());
				output.accept(ModItems.FRESH_SEGISAURUS_SKULL.get());
				output.accept(ModItems.FRESH_SHANTUNGOSAURUS_SKULL.get());
				output.accept(ModItems.FRESH_STEGOSAURUS_SKULL.get());
				output.accept(ModItems.FRESH_STYRACOSAURUS_SKULL.get());
				output.accept(ModItems.FRESH_SUCHOMIMUS_SKULL.get());
				output.accept(ModItems.FRESH_TAPEJARA_SKULL.get());
				output.accept(ModItems.FRESH_THERIZINOSAURUS_SKULL.get());
				output.accept(ModItems.FRESH_THESCELOSAURUS_SKULL.get());
				output.accept(ModItems.FRESH_TITANOSAURUS_SKULL.get());
				output.accept(ModItems.FRESH_TRICERATOPS_SKULL.get());
				output.accept(ModItems.FRESH_TROODON_SKULL.get());
				output.accept(ModItems.FRESH_TROPEOGNATHUS_SKULL.get());
				output.accept(ModItems.FRESH_TUPUXUARA_SKULL.get());
				output.accept(ModItems.FRESH_TYRANNOSAURUS_REX_SKULL.get());
				output.accept(ModItems.FRESH_UTAHRAPTOR_SKULL.get());
				output.accept(ModItems.FRESH_VELOCIRAPTOR_SKULL.get());
				output.accept(ModItems.FRESH_ZHENYUANOPTERUS_SKULL.get());

// Tissue (alphabetical)
				output.accept(ModItems.ACHILLOBATOR_TISSUE.get());
				output.accept(ModItems.ALBERTOSAURUS_TISSUE.get());
				output.accept(ModItems.ALLOSAURUS_TISSUE.get());
				output.accept(ModItems.ALVAREZSAURUS_TISSUE.get());
				output.accept(ModItems.ANKYLOSAURUS_TISSUE.get());
				output.accept(ModItems.APATOSAURUS_TISSUE.get());
				output.accept(ModItems.ARAMBOURGIANIA_TISSUE.get());
				output.accept(ModItems.BARYONYX_TISSUE.get());
				output.accept(ModItems.BRACHIOSAURUS_TISSUE.get());
				output.accept(ModItems.CARCHARODONTOSAURUS_TISSUE.get());
				output.accept(ModItems.CARNOTAURUS_TISSUE.get());
				output.accept(ModItems.CEARADACTYLUS_TISSUE.get());
				output.accept(ModItems.CERATOSAURUS_TISSUE.get());
				output.accept(ModItems.CHASMOSAURUS_TISSUE.get());
				output.accept(ModItems.CHILESAURUS_TISSUE.get());
				output.accept(ModItems.COELOPHYSIS_TISSUE.get());
				output.accept(ModItems.COELURUS_TISSUE.get());
				output.accept(ModItems.COMPSOGNATHUS_TISSUE.get());
				output.accept(ModItems.CONCAVENATOR_TISSUE.get());
				output.accept(ModItems.CORYTHOSAURUS_TISSUE.get());
				output.accept(ModItems.DEINONYCHUS_TISSUE.get());
				output.accept(ModItems.DILOPHOSAURUS_TISSUE.get());
				output.accept(ModItems.DIMORPHODON_TISSUE.get());
				output.accept(ModItems.DIPLODOCUS_TISSUE.get());
				output.accept(ModItems.DISTORTUS_REX_TISSUE.get());
				output.accept(ModItems.DRYOSAURUS_TISSUE.get());
				output.accept(ModItems.EDMONTOSAURUS_TISSUE.get());
				output.accept(ModItems.GALLIMIMUS_TISSUE.get());
				output.accept(ModItems.GEOSTERNBERGIA_TISSUE.get());
				output.accept(ModItems.GIGANOTOSAURUS_TISSUE.get());
				output.accept(ModItems.GUANLONG_TISSUE.get());
				output.accept(ModItems.GUIDRACO_TISSUE.get());
				output.accept(ModItems.HADROSAURUS_TISSUE.get());
				output.accept(ModItems.HERRERASAURUS_TISSUE.get());
				output.accept(ModItems.HYPSILOPHODON_TISSUE.get());
				output.accept(ModItems.INDOMINUS_REX_TISSUE.get());
				output.accept(ModItems.INDORAPTOR_TISSUE.get());
				output.accept(ModItems.INOSTRANCEVIA_TISSUE.get());
				output.accept(ModItems.LAMBEOSAURUS_TISSUE.get());
				output.accept(ModItems.LUDODACTYLUS_TISSUE.get());
				output.accept(ModItems.MAJUNGASAURUS_TISSUE.get());
				output.accept(ModItems.MAMENCHISAURUS_TISSUE.get());
				output.accept(ModItems.METRIACANTHOSAURUS_TISSUE.get());
				output.accept(ModItems.MOGANOPTERUS_TISSUE.get());
				output.accept(ModItems.MUSSASAURUS_TISSUE.get());
				output.accept(ModItems.NYCTOSAURUS_TISSUE.get());
				output.accept(ModItems.ORNITHOLESTES_TISSUE.get());
				output.accept(ModItems.ORNITHOMIMUS_TISSUE.get());
				output.accept(ModItems.OURANOSAURUS_TISSUE.get());
				output.accept(ModItems.OVIRAPTOR_TISSUE.get());
				output.accept(ModItems.PACHYCEPHALOSAURUS_TISSUE.get());
				output.accept(ModItems.PARASAUROLOPHUS_TISSUE.get());
				output.accept(ModItems.PROCERATOSAURUS_TISSUE.get());
				output.accept(ModItems.PROCOMPSOGNATHUS_TISSUE.get());
				output.accept(ModItems.PROTOCERATOPS_TISSUE.get());
				output.accept(ModItems.PTERANODON_TISSUE.get());
				output.accept(ModItems.PTERODAUSTRO_TISSUE.get());
				output.accept(ModItems.QUETZALCOATLUS_TISSUE.get());
				output.accept(ModItems.RAJASAURUS_TISSUE.get());
				output.accept(ModItems.RUGOPS_TISSUE.get());
				output.accept(ModItems.SEGISAURUS_TISSUE.get());
				output.accept(ModItems.SHANTUNGOSAURUS_TISSUE.get());
				output.accept(ModItems.SPINOSAURUS_TISSUE.get());
				output.accept(ModItems.STEGOSAURUS_TISSUE.get());
				output.accept(ModItems.STYRACOSAURUS_TISSUE.get());
				output.accept(ModItems.SUCHOMIMUS_TISSUE.get());
				output.accept(ModItems.TAPEJARA_TISSUE.get());
				output.accept(ModItems.THERIZINOSAURUS_TISSUE.get());
				output.accept(ModItems.THESCELOSAURUS_TISSUE.get());
				output.accept(ModItems.TITANOSAURUS_TISSUE.get());
				output.accept(ModItems.TRICERATOPS_TISSUE.get());
				output.accept(ModItems.TROODON_TISSUE.get());
				output.accept(ModItems.TROPEOGNATHUS_TISSUE.get());
				output.accept(ModItems.TUPUXUARA_TISSUE.get());
				output.accept(ModItems.TYRANNOSAURUS_REX_TISSUE.get());
				output.accept(ModItems.UTAHRAPTOR_TISSUE.get());
				output.accept(ModItems.VELOCIRAPTOR_TISSUE.get());
				output.accept(ModItems.ZHENYUANOPTERUS_TISSUE.get());

// DNA (alphabetical)
				output.accept(ModItems.ACHILLOBATOR_DNA.get());
				output.accept(ModItems.ALBERTOSAURUS_DNA.get());
				output.accept(ModItems.ALLOSAURUS_DNA.get());
				output.accept(ModItems.ALVAREZSAURUS_DNA.get());
				output.accept(ModItems.ANKYLOSAURUS_DNA.get());
				output.accept(ModItems.APATOSAURUS_DNA.get());
				output.accept(ModItems.ARAMBOURGIANIA_DNA.get());
				output.accept(ModItems.BARYONYX_DNA.get());
				output.accept(ModItems.BRACHIOSAURUS_DNA.get());
				output.accept(ModItems.CARCHARODONTOSAURUS_DNA.get());
				output.accept(ModItems.CARNOTAURUS_DNA.get());
				output.accept(ModItems.CEARADACTYLUS_DNA.get());
				output.accept(ModItems.CERATOSAURUS_DNA.get());
				output.accept(ModItems.CHASMOSAURUS_DNA.get());
				output.accept(ModItems.CHILESAURUS_DNA.get());
				output.accept(ModItems.COELOPHYSIS_DNA.get());
				output.accept(ModItems.COELURUS_DNA.get());
				output.accept(ModItems.COMPSOGNATHUS_DNA.get());
				output.accept(ModItems.CONCAVENATOR_DNA.get());
				output.accept(ModItems.CORYTHOSAURUS_DNA.get());
				output.accept(ModItems.DEINONYCHUS_DNA.get());
				output.accept(ModItems.DILOPHOSAURUS_DNA.get());
				output.accept(ModItems.DIMORPHODON_DNA.get());
				output.accept(ModItems.DIPLODOCUS_DNA.get());
				output.accept(ModItems.DISTORTUS_REX_DNA.get());
				output.accept(ModItems.DRYOSAURUS_DNA.get());
				output.accept(ModItems.EDMONTOSAURUS_DNA.get());
				output.accept(ModItems.GALLIMIMUS_DNA.get());
				output.accept(ModItems.GEOSTERNBERGIA_DNA.get());
				output.accept(ModItems.GIGANOTOSAURUS_DNA.get());
				output.accept(ModItems.GUANLONG_DNA.get());
				output.accept(ModItems.GUIDRACO_DNA.get());
				output.accept(ModItems.HADROSAURUS_DNA.get());
				output.accept(ModItems.HERRERASAURUS_DNA.get());
				output.accept(ModItems.HYPSILOPHODON_DNA.get());
				output.accept(ModItems.INDOMINUS_REX_DNA.get());
				output.accept(ModItems.INDORAPTOR_DNA.get());
				output.accept(ModItems.INOSTRANCEVIA_DNA.get());
				output.accept(ModItems.LAMBEOSAURUS_DNA.get());
				output.accept(ModItems.LUDODACTYLUS_DNA.get());
				output.accept(ModItems.MAJUNGASAURUS_DNA.get());
				output.accept(ModItems.MAMENCHISAURUS_DNA.get());
				output.accept(ModItems.METRIACANTHOSAURUS_DNA.get());
				output.accept(ModItems.MOGANOPTERUS_DNA.get());
				output.accept(ModItems.MUSSASAURUS_DNA.get());
				output.accept(ModItems.NYCTOSAURUS_DNA.get());
				output.accept(ModItems.ORNITHOLESTES_DNA.get());
				output.accept(ModItems.ORNITHOMIMUS_DNA.get());
				output.accept(ModItems.OURANOSAURUS_DNA.get());
				output.accept(ModItems.OVIRAPTOR_DNA.get());
				output.accept(ModItems.PACHYCEPHALOSAURUS_DNA.get());
				output.accept(ModItems.PARASAUROLOPHUS_DNA.get());
				output.accept(ModItems.PROCERATOSAURUS_DNA.get());
				output.accept(ModItems.PROCOMPSOGNATHUS_DNA.get());
				output.accept(ModItems.PROTOCERATOPS_DNA.get());
				output.accept(ModItems.PTERANODON_DNA.get());
				output.accept(ModItems.PTERODAUSTRO_DNA.get());
				output.accept(ModItems.QUETZALCOATLUS_DNA.get());
				output.accept(ModItems.RAJASAURUS_DNA.get());
				output.accept(ModItems.RUGOPS_DNA.get());
				output.accept(ModItems.SEGISAURUS_DNA.get());
				output.accept(ModItems.SHANTUNGOSAURUS_DNA.get());
				output.accept(ModItems.SPINOSAURUS_DNA.get());
				output.accept(ModItems.STEGOSAURUS_DNA.get());
				output.accept(ModItems.STYRACOSAURUS_DNA.get());
				output.accept(ModItems.SUCHOMIMUS_DNA.get());
				output.accept(ModItems.TAPEJARA_DNA.get());
				output.accept(ModItems.THERIZINOSAURUS_DNA.get());
				output.accept(ModItems.THESCELOSAURUS_DNA.get());
				output.accept(ModItems.TITANOSAURUS_DNA.get());
				output.accept(ModItems.TRICERATOPS_DNA.get());
				output.accept(ModItems.TROODON_DNA.get());
				output.accept(ModItems.TROPEOGNATHUS_DNA.get());
				output.accept(ModItems.TUPUXUARA_DNA.get());
				output.accept(ModItems.TYRANNOSAURUS_REX_DNA.get());
				output.accept(ModItems.UTAHRAPTOR_DNA.get());
				output.accept(ModItems.VELOCIRAPTOR_DNA.get());
				output.accept(ModItems.ZHENYUANOPTERUS_DNA.get());

// Syringes (alphabetical)
				output.accept(ModItems.ACHILLOBATOR_SYRINGE.get());
				output.accept(ModItems.ALBERTOSAURUS_SYRINGE.get());
				output.accept(ModItems.ALLOSAURUS_SYRINGE.get());
				output.accept(ModItems.ALVAREZSAURUS_SYRINGE.get());
				output.accept(ModItems.ANKYLOSAURUS_SYRINGE.get());
				output.accept(ModItems.APATOSAURUS_SYRINGE.get());
				output.accept(ModItems.ARAMBOURGIANIA_SYRINGE.get());
				output.accept(ModItems.BARYONYX_SYRINGE.get());
				output.accept(ModItems.BRACHIOSAURUS_SYRINGE.get());
				output.accept(ModItems.CARCHARODONTOSAURUS_SYRINGE.get());
				output.accept(ModItems.CARNOTAURUS_SYRINGE.get());
				output.accept(ModItems.CEARADACTYLUS_SYRINGE.get());
				output.accept(ModItems.CERATOSAURUS_SYRINGE.get());
				output.accept(ModItems.CHASMOSAURUS_SYRINGE.get());
				output.accept(ModItems.CHILESAURUS_SYRINGE.get());
				output.accept(ModItems.COELOPHYSIS_SYRINGE.get());
				output.accept(ModItems.COELURUS_SYRINGE.get());
				output.accept(ModItems.COMPSOGNATHUS_SYRINGE.get());
				output.accept(ModItems.CONCAVENATOR_SYRINGE.get());
				output.accept(ModItems.CORYTHOSAURUS_SYRINGE.get());
				output.accept(ModItems.DEINONYCHUS_SYRINGE.get());
				output.accept(ModItems.DILOPHOSAURUS_SYRINGE.get());
				output.accept(ModItems.DIMORPHODON_SYRINGE.get());
				output.accept(ModItems.DIPLODOCUS_SYRINGE.get());
				output.accept(ModItems.DISTORTUS_REX_SYRINGE.get());
				output.accept(ModItems.DRYOSAURUS_SYRINGE.get());
				output.accept(ModItems.EDMONTOSAURUS_SYRINGE.get());
				output.accept(ModItems.GALLIMIMUS_SYRINGE.get());
				output.accept(ModItems.GEOSTERNBERGIA_SYRINGE.get());
				output.accept(ModItems.GIGANOTOSAURUS_SYRINGE.get());
				output.accept(ModItems.GUANLONG_SYRINGE.get());
				output.accept(ModItems.GUIDRACO_SYRINGE.get());
				output.accept(ModItems.HADROSAURUS_SYRINGE.get());
				output.accept(ModItems.HERRERASAURUS_SYRINGE.get());
				output.accept(ModItems.HYPSILOPHODON_SYRINGE.get());
				output.accept(ModItems.INDOMINUS_REX_SYRINGE.get());
				output.accept(ModItems.INDORAPTOR_SYRINGE.get());
				output.accept(ModItems.INOSTRANCEVIA_SYRINGE.get());
				output.accept(ModItems.LAMBEOSAURUS_SYRINGE.get());
				output.accept(ModItems.LUDODACTYLUS_SYRINGE.get());
				output.accept(ModItems.MAJUNGASAURUS_SYRINGE.get());
				output.accept(ModItems.MAMENCHISAURUS_SYRINGE.get());
				output.accept(ModItems.METRIACANTHOSAURUS_SYRINGE.get());
				output.accept(ModItems.MOGANOPTERUS_SYRINGE.get());
				output.accept(ModItems.MUSSASAURUS_SYRINGE.get());
				output.accept(ModItems.NYCTOSAURUS_SYRINGE.get());
				output.accept(ModItems.ORNITHOLESTES_SYRINGE.get());
				output.accept(ModItems.ORNITHOMIMUS_SYRINGE.get());
				output.accept(ModItems.OURANOSAURUS_SYRINGE.get());
				output.accept(ModItems.OVIRAPTOR_SYRINGE.get());
				output.accept(ModItems.PACHYCEPHALOSAURUS_SYRINGE.get());
				output.accept(ModItems.PARASAUROLOPHUS_SYRINGE.get());
				output.accept(ModItems.PROCERATOSAURUS_SYRINGE.get());
				output.accept(ModItems.PROCOMPSOGNATHUS_SYRINGE.get());
				output.accept(ModItems.PROTOCERATOPS_SYRINGE.get());
				output.accept(ModItems.PTERANODON_SYRINGE.get());
				output.accept(ModItems.PTERODAUSTRO_SYRINGE.get());
				output.accept(ModItems.QUETZALCOATLUS_SYRINGE.get());
				output.accept(ModItems.RAJASAURUS_SYRINGE.get());
				output.accept(ModItems.RUGOPS_SYRINGE.get());
				output.accept(ModItems.SEGISAURUS_SYRINGE.get());
				output.accept(ModItems.SHANTUNGOSAURUS_SYRINGE.get());
				output.accept(ModItems.SPINOSAURUS_SYRINGE.get());
				output.accept(ModItems.STEGOSAURUS_SYRINGE.get());
				output.accept(ModItems.STYRACOSAURUS_SYRINGE.get());
				output.accept(ModItems.SUCHOMIMUS_SYRINGE.get());
				output.accept(ModItems.TAPEJARA_SYRINGE.get());
				output.accept(ModItems.THERIZINOSAURUS_SYRINGE.get());
				output.accept(ModItems.THESCELOSAURUS_SYRINGE.get());
				output.accept(ModItems.TITANOSAURUS_SYRINGE.get());
				output.accept(ModItems.TRICERATOPS_SYRINGE.get());
				output.accept(ModItems.TROODON_SYRINGE.get());
				output.accept(ModItems.TROPEOGNATHUS_SYRINGE.get());
				output.accept(ModItems.TUPUXUARA_SYRINGE.get());
				output.accept(ModItems.TYRANNOSAURUS_REX_SYRINGE.get());
				output.accept(ModItems.UTAHRAPTOR_SYRINGE.get());
				output.accept(ModItems.VELOCIRAPTOR_SYRINGE.get());
				output.accept(ModItems.ZHENYUANOPTERUS_SYRINGE.get());

// Eggs (alphabetical)
				output.accept(ModBlocks.ACHILLOBATOR_EGG.get());
				output.accept(ModBlocks.ALBERTOSAURUS_EGG.get());
				output.accept(ModBlocks.ALLOSAURUS_EGG.get());
				output.accept(ModBlocks.ALVAREZSAURUS_EGG.get());
				output.accept(ModBlocks.ANKYLOSAURUS_EGG.get());
				output.accept(ModBlocks.APATOSAURUS_EGG.get());
				output.accept(ModBlocks.ARAMBOURGIANIA_EGG.get());
				output.accept(ModBlocks.BARYONYX_EGG.get());
				output.accept(ModBlocks.BRACHIOSAURUS_EGG.get());
				output.accept(ModBlocks.CARCHARODONTOSAURUS_EGG.get());
				output.accept(ModBlocks.CARNOTAURUS_EGG.get());
				output.accept(ModBlocks.CEARADACTYLUS_EGG.get());
				output.accept(ModBlocks.CERATOSAURUS_EGG.get());
				output.accept(ModBlocks.CHASMOSAURUS_EGG.get());
				output.accept(ModBlocks.CHILESAURUS_EGG.get());
				output.accept(ModBlocks.COELOPHYSIS_EGG.get());
				output.accept(ModBlocks.COELURUS_EGG.get());
				output.accept(ModBlocks.COMPSOGNATHUS_EGG.get());
				output.accept(ModBlocks.CONCAVENATOR_EGG.get());
				output.accept(ModBlocks.CORYTHOSAURUS_EGG.get());
				output.accept(ModBlocks.DEINONYCHUS_EGG.get());
				output.accept(ModBlocks.DILOPHOSAURUS_EGG.get());
				output.accept(ModBlocks.DIMORPHODON_EGG.get());
				output.accept(ModBlocks.DIPLODOCUS_EGG.get());
				output.accept(ModBlocks.DISTORTUS_REX_EGG.get());
				output.accept(ModBlocks.DRYOSAURUS_EGG.get());
				output.accept(ModBlocks.EDMONTOSAURUS_EGG.get());
				output.accept(ModBlocks.GALLIMIMUS_EGG.get());
				output.accept(ModBlocks.GEOSTERNBERGIA_EGG.get());
				output.accept(ModBlocks.GIGANOTOSAURUS_EGG.get());
				output.accept(ModBlocks.GUANLONG_EGG.get());
				output.accept(ModBlocks.GUIDRACO_EGG.get());
				output.accept(ModBlocks.HADROSAURUS_EGG.get());
				output.accept(ModBlocks.HERRERASAURUS_EGG.get());
				output.accept(ModBlocks.HYPSILOPHODON_EGG.get());
				output.accept(ModBlocks.INDOMINUS_REX_EGG.get());
				output.accept(ModBlocks.INDORAPTOR_EGG.get());
				output.accept(ModBlocks.INOSTRANCEVIA_EGG.get());
				output.accept(ModBlocks.LAMBEOSAURUS_EGG.get());
				output.accept(ModBlocks.LUDODACTYLUS_EGG.get());
				output.accept(ModBlocks.MAJUNGASAURUS_EGG.get());
				output.accept(ModBlocks.MAMENCHISAURUS_EGG.get());
				output.accept(ModBlocks.METRIACANTHOSAURUS_EGG.get());
				output.accept(ModBlocks.MOGANOPTERUS_EGG.get());
				output.accept(ModBlocks.MUSSASAURUS_EGG.get());
				output.accept(ModBlocks.NYCTOSAURUS_EGG.get());
				output.accept(ModBlocks.ORNITHOLESTES_EGG.get());
				output.accept(ModBlocks.ORNITHOMIMUS_EGG.get());
				output.accept(ModBlocks.OURANOSAURUS_EGG.get());
				output.accept(ModBlocks.OVIRAPTOR_EGG.get());
				output.accept(ModBlocks.PACHYCEPHALOSAURUS_EGG.get());
				output.accept(ModBlocks.PROCERATOSAURUS_EGG.get());
				output.accept(ModBlocks.PROCOMPSOGNATHUS_EGG.get());
				output.accept(ModBlocks.PROTOCERATOPS_EGG.get());
				output.accept(ModBlocks.PTERANODON_EGG.get());
				output.accept(ModBlocks.PTERODAUSTRO_EGG.get());
				output.accept(ModBlocks.QUETZALCOATLUS_EGG.get());
				output.accept(ModBlocks.RAJASAURUS_EGG.get());
				output.accept(ModBlocks.RUGOPS_EGG.get());
				output.accept(ModBlocks.SEGISAURUS_EGG.get());
				output.accept(ModBlocks.SHANTUNGOSAURUS_EGG.get());
				output.accept(ModBlocks.SPINOSAURUS_EGG.get());
				output.accept(ModBlocks.STEGOSAURUS_EGG.get());
				output.accept(ModBlocks.STYRACOSAURUS_EGG.get());
				output.accept(ModBlocks.SUCHOMIMUS_EGG.get());
				output.accept(ModBlocks.TAPEJARA_EGG.get());
				output.accept(ModBlocks.THERIZINOSAURUS_EGG.get());
				output.accept(ModBlocks.THESCELOSAURUS_EGG.get());
				output.accept(ModBlocks.TITANOSAURUS_EGG.get());
				output.accept(ModBlocks.TRICERATOPS_EGG.get());
				output.accept(ModBlocks.TROODON_EGG.get());
				output.accept(ModBlocks.TROPEOGNATHUS_EGG.get());
				output.accept(ModBlocks.TUPUXUARA_EGG.get());
				output.accept(ModBlocks.TYRANNOSAURUS_REX_EGG.get());
				output.accept(ModBlocks.UTAHRAPTOR_EGG.get());
				output.accept(ModBlocks.VELOCIRAPTOR_EGG.get());
				output.accept(ModBlocks.ZHENYUANOPTERUS_EGG.get());
			});
		}));

	public static final RegistrySupplier<CreativeModeTab> DINO_TAB = TABS.register("dino_tab",
		() -> CreativeTabRegistry.create(builder -> {
			builder.title(Component.translatable("itemGroup." + Constants.MOD_ID + ".dino_tab"));
			builder.icon(() -> new ItemStack(ModItems.TYRANNOSAURUS_REX_SPAWN_EGG.get().asItem()));
			builder.displayItems((params, output) -> {
				output.accept(ModItems.ACHILLOBATOR_SPAWN_EGG.get());
				output.accept(ModItems.ALBERTOSAURUS_SPAWN_EGG.get());
				output.accept(ModItems.ALLOSAURUS_SPAWN_EGG.get());
				output.accept(ModItems.ALVAREZSAURUS_SPAWN_EGG.get());
				output.accept(ModItems.ANKYLOSAURUS_SPAWN_EGG.get());
				output.accept(ModItems.APATOSAURUS_SPAWN_EGG.get());
				output.accept(ModItems.ARAMBOURGIANIA_SPAWN_EGG.get());
				output.accept(ModItems.BARYONYX_SPAWN_EGG.get());
				output.accept(ModItems.BRACHIOSAURUS_SPAWN_EGG.get());
				output.accept(ModItems.CARCHARODONTOSAURUS_SPAWN_EGG.get());
				output.accept(ModItems.CARNOTAURUS_SPAWN_EGG.get());
				output.accept(ModItems.CEARADACTYLUS_SPAWN_EGG.get());
				output.accept(ModItems.CERATOSAURUS_SPAWN_EGG.get());
				output.accept(ModItems.CHASMOSAURUS_SPAWN_EGG.get());
				output.accept(ModItems.CHILESAURUS_SPAWN_EGG.get());
				output.accept(ModItems.COELOPHYSIS_SPAWN_EGG.get());
				output.accept(ModItems.COELURUS_SPAWN_EGG.get());
				output.accept(ModItems.COMPSOGNATHUS_SPAWN_EGG.get());
				output.accept(ModItems.CONCAVENATOR_SPAWN_EGG.get());
				output.accept(ModItems.CORYTHOSAURUS_SPAWN_EGG.get());
				output.accept(ModItems.DEINONYCHUS_SPAWN_EGG.get());
				output.accept(ModItems.DILOPHOSAURUS_SPAWN_EGG.get());
				output.accept(ModItems.DIMORPHODON_SPAWN_EGG.get());
				output.accept(ModItems.DIPLODOCUS_SPAWN_EGG.get());
				output.accept(ModItems.DISTORTUS_REX_SPAWN_EGG.get());
				output.accept(ModItems.DRYOSAURUS_SPAWN_EGG.get());
				output.accept(ModItems.EDMONTOSAURUS_SPAWN_EGG.get());
				output.accept(ModItems.GALLIMIMUS_SPAWN_EGG.get());
				output.accept(ModItems.GEOSTERNBERGIA_SPAWN_EGG.get());
				output.accept(ModItems.GIGANOTOSAURUS_SPAWN_EGG.get());
				output.accept(ModItems.GUANLONG_SPAWN_EGG.get());
				output.accept(ModItems.GUIDRACO_SPAWN_EGG.get());
				output.accept(ModItems.HADROSAURUS_SPAWN_EGG.get());
				output.accept(ModItems.HERRERASAURUS_SPAWN_EGG.get());
				output.accept(ModItems.HYPSILOPHODON_SPAWN_EGG.get());
				output.accept(ModItems.INDOMINUS_REX_SPAWN_EGG.get());
				output.accept(ModItems.INDORAPTOR_SPAWN_EGG.get());
				output.accept(ModItems.INOSTRANCEVIA_SPAWN_EGG.get());
				output.accept(ModItems.LAMBEOSAURUS_SPAWN_EGG.get());
				output.accept(ModItems.LUDODACTYLUS_SPAWN_EGG.get());
				output.accept(ModItems.MAJUNGASAURUS_SPAWN_EGG.get());
				output.accept(ModItems.MAMENCHISAURUS_SPAWN_EGG.get());
				output.accept(ModItems.METRIACANTHOSAURUS_SPAWN_EGG.get());
				output.accept(ModItems.MOGANOPTERUS_SPAWN_EGG.get());
				output.accept(ModItems.MUSSASAURUS_SPAWN_EGG.get());
				output.accept(ModItems.NYCTOSAURUS_SPAWN_EGG.get());
				output.accept(ModItems.ORNITHOLESTES_SPAWN_EGG.get());
				output.accept(ModItems.ORNITHOMIMUS_SPAWN_EGG.get());
				output.accept(ModItems.OURANOSAURUS_SPAWN_EGG.get());
				output.accept(ModItems.OVIRAPTOR_SPAWN_EGG.get());
				output.accept(ModItems.PACHYCEPHALOSAURUS_SPAWN_EGG.get());
				output.accept(ModItems.PARASAUROLOPHUS_SPAWN_EGG.get());
				output.accept(ModItems.PROCERATOSAURUS_SPAWN_EGG.get());
				output.accept(ModItems.PROCOMPSOGNATHUS_SPAWN_EGG.get());
				output.accept(ModItems.PROTOCERATOPS_SPAWN_EGG.get());
				output.accept(ModItems.PTERANODON_SPAWN_EGG.get());
				output.accept(ModItems.PTERODAUSTRO_SPAWN_EGG.get());
				output.accept(ModItems.QUETZALCOATLUS_SPAWN_EGG.get());
				output.accept(ModItems.RAJASAURUS_SPAWN_EGG.get());
				output.accept(ModItems.RUGOPS_SPAWN_EGG.get());
				output.accept(ModItems.SEGISAURUS_SPAWN_EGG.get());
				output.accept(ModItems.SHANTUNGOSAURUS_SPAWN_EGG.get());
				output.accept(ModItems.SPINOSAURUS_SPAWN_EGG.get());
				output.accept(ModItems.STEGOSAURUS_SPAWN_EGG.get());
				output.accept(ModItems.STYRACOSAURUS_SPAWN_EGG.get());
				output.accept(ModItems.SUCHOMIMUS_SPAWN_EGG.get());
				output.accept(ModItems.TAPEJARA_SPAWN_EGG.get());
				output.accept(ModItems.THERIZINOSAURUS_SPAWN_EGG.get());
				output.accept(ModItems.THESCELOSAURUS_SPAWN_EGG.get());
				output.accept(ModItems.TITANOSAURUS_SPAWN_EGG.get());
				output.accept(ModItems.TRICERATOPS_SPAWN_EGG.get());
				output.accept(ModItems.TROODON_SPAWN_EGG.get());
				output.accept(ModItems.TROPEOGNATHUS_SPAWN_EGG.get());
				output.accept(ModItems.TUPUXUARA_SPAWN_EGG.get());
				output.accept(ModItems.TYRANNOSAURUS_REX_SPAWN_EGG.get());
				output.accept(ModItems.UTAHRAPTOR_SPAWN_EGG.get());
				output.accept(ModItems.VELOCIRAPTOR_SPAWN_EGG.get());
				output.accept(ModItems.ZHENYUANOPTERUS_SPAWN_EGG.get());
			});
		}));

	public static void register() {
		TABS.register();
	}
}