package net.cmr.jurassicrevived.datagen;

import net.cmr.jurassicrevived.block.ModBlocks;
import net.cmr.jurassicrevived.item.ModItems;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;

public class ModItemModelProvider {

    public interface ItemModelHelper {
        void basicItemModel(Item item); // Renamed from basicItem
        void spawnEgg(Item item);
        void simpleBlockItemModel(Block block); // Renamed from simpleBlockItem
        void flowerItem(Block block);
        void wallItem(Block block, Block baseBlock);
        void buttonItem(Block block, Block baseBlock);
        void fenceItem(Block block, Block baseBlock);
        void withExistingParentModel(Item item, ResourceLocation parent); // Renamed from withExistingParent
    }

    public static void registerItemModels(ItemModelHelper helper) {
        helper.spawnEgg(ModItems.APATOSAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.ALBERTOSAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.BRACHIOSAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.CERATOSAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.COMPSOGNATHUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.DILOPHOSAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.DIPLODOCUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.FDUCK_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.OURANOSAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.GALLIMIMUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.INDOMINUS_REX_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.PARASAUROLOPHUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.SPINOSAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.TRICERATOPS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.TYRANNOSAURUS_REX_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.VELOCIRAPTOR_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.BARYONYX_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.CARNOTAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.CONCAVENATOR_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.DEINONYCHUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.DISTORTUS_REX_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.EDMONTOSAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.GIGANOTOSAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.GUANLONG_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.HERRERASAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.MAJUNGASAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.PROCOMPSOGNATHUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.PROTOCERATOPS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.ARAMBOURGIANIA_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.CEARADACTYLUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.DIMORPHODON_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.GEOSTERNBERGIA_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.GUIDRACO_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.LUDODACTYLUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.MOGANOPTERUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.NYCTOSAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.PTERANODON_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.PTERODAUSTRO_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.QUETZALCOATLUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.TAPEJARA_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.TROPEOGNATHUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.TUPUXUARA_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.ZHENYUANOPTERUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.RUGOPS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.SHANTUNGOSAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.STEGOSAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.STYRACOSAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.THERIZINOSAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.CHICKENOSAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.ALLOSAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.ALVAREZSAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.ANKYLOSAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.CARCHARODONTOSAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.CHASMOSAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.COELOPHYSIS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.COELURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.CORYTHOSAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.DRYOSAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.HADROSAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.HYPSILOPHODON_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.INDORAPTOR_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.INOSTRANCEVIA_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.LAMBEOSAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.MAMENCHISAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.METRIACANTHOSAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.ORNITHOLESTES_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.ORNITHOMIMUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.OVIRAPTOR_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.PACHYCEPHALOSAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.PROCERATOSAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.RAJASAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.SEGISAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.TITANOSAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.TROODON_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.UTAHRAPTOR_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.ACHILLOBATOR_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.SUCHOMIMUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.CHILESAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.THESCELOSAURUS_SPAWN_EGG.get());
        helper.spawnEgg(ModItems.MUSSASAURUS_SPAWN_EGG.get());

        helper.basicItemModel(ModItems.FROG_MATERIAL.get());
        helper.basicItemModel(ModItems.FROG_DNA.get());

        helper.basicItemModel(ModItems.TEST_TUBE.get());
        helper.basicItemModel(ModItems.SYRINGE.get());
        helper.basicItemModel(ModItems.CRUSHED_FOSSIL.get());
        helper.basicItemModel(ModItems.MOSQUITO_IN_AMBER.get());
        helper.basicItemModel(ModItems.FROZEN_LEECH.get());
        helper.basicItemModel(ModItems.FROZEN_BONE.get());
        helper.basicItemModel(ModItems.CABLE.get());
        helper.basicItemModel(ModItems.SCREEN.get());
        helper.basicItemModel(ModItems.PROCESSOR.get());
        helper.basicItemModel(ModItems.TIRE.get());
        helper.basicItemModel(ModItems.CUTTING_BLADES.get());
        helper.basicItemModel(ModItems.WRENCH.get());
        
		helper.basicItemModel(ModItems.MAC_N_CHEESE.get());
        helper.basicItemModel(ModItems.WALNUT_PUMPKIN_PIE.get());
        helper.basicItemModel(ModItems.BANANA_NUT_COOKIE.get());

        helper.basicItemModel(ModItems.APATOSAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.ALBERTOSAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.BRACHIOSAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.CERATOSAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.COMPSOGNATHUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.DILOPHOSAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.DIPLODOCUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.GALLIMIMUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.PARASAUROLOPHUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.OURANOSAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.SPINOSAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.TRICERATOPS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.TYRANNOSAURUS_REX_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.VELOCIRAPTOR_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.BARYONYX_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.CARNOTAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.CONCAVENATOR_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.DEINONYCHUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.EDMONTOSAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.GIGANOTOSAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.GUANLONG_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.HERRERASAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.MAJUNGASAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.PROCOMPSOGNATHUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.PROTOCERATOPS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.RUGOPS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.SHANTUNGOSAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.STEGOSAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.STYRACOSAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.THERIZINOSAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.ALLOSAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.ALVAREZSAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.ANKYLOSAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.ARAMBOURGIANIA_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.CARCHARODONTOSAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.CEARADACTYLUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.CHASMOSAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.COELOPHYSIS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.COELURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.CORYTHOSAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.DIMORPHODON_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.DRYOSAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.GEOSTERNBERGIA_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.GUIDRACO_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.HADROSAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.HYPSILOPHODON_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.INOSTRANCEVIA_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.LAMBEOSAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.LUDODACTYLUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.MAMENCHISAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.METRIACANTHOSAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.MOGANOPTERUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.NYCTOSAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.ORNITHOLESTES_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.ORNITHOMIMUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.OVIRAPTOR_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.PACHYCEPHALOSAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.PROCERATOSAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.PTERANODON_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.PTERODAUSTRO_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.QUETZALCOATLUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.RAJASAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.SEGISAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.TAPEJARA_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.TITANOSAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.TROODON_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.TROPEOGNATHUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.TUPUXUARA_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.UTAHRAPTOR_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.ZHENYUANOPTERUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.ACHILLOBATOR_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.SUCHOMIMUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.CHILESAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.THESCELOSAURUS_SKULL_FOSSIL.get());
        helper.basicItemModel(ModItems.MUSSASAURUS_SKULL_FOSSIL.get());

        helper.basicItemModel(ModItems.FRESH_APATOSAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_ALBERTOSAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_BRACHIOSAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_CERATOSAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_COMPSOGNATHUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_DILOPHOSAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_DIPLODOCUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_GALLIMIMUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_INDOMINUS_REX_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_PARASAUROLOPHUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_OURANOSAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_SPINOSAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_TRICERATOPS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_TYRANNOSAURUS_REX_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_VELOCIRAPTOR_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_BARYONYX_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_CARNOTAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_CONCAVENATOR_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_DEINONYCHUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_EDMONTOSAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_GIGANOTOSAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_GUANLONG_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_HERRERASAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_MAJUNGASAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_PROCOMPSOGNATHUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_PROTOCERATOPS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_RUGOPS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_SHANTUNGOSAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_STEGOSAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_STYRACOSAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_THERIZINOSAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_DISTORTUS_REX_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_ALLOSAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_ALVAREZSAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_ANKYLOSAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_ARAMBOURGIANIA_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_CARCHARODONTOSAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_CEARADACTYLUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_CHASMOSAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_COELOPHYSIS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_COELURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_CORYTHOSAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_DIMORPHODON_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_DRYOSAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_GEOSTERNBERGIA_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_GUIDRACO_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_HADROSAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_HYPSILOPHODON_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_INDORAPTOR_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_INOSTRANCEVIA_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_LAMBEOSAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_LUDODACTYLUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_MAMENCHISAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_METRIACANTHOSAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_MOGANOPTERUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_NYCTOSAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_ORNITHOLESTES_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_ORNITHOMIMUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_OVIRAPTOR_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_PACHYCEPHALOSAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_PROCERATOSAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_PTERANODON_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_PTERODAUSTRO_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_QUETZALCOATLUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_RAJASAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_SEGISAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_TAPEJARA_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_TITANOSAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_TROODON_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_TROPEOGNATHUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_TUPUXUARA_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_UTAHRAPTOR_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_ZHENYUANOPTERUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_ACHILLOBATOR_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_SUCHOMIMUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_CHILESAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_THESCELOSAURUS_SKULL.get());
        helper.basicItemModel(ModItems.FRESH_MUSSASAURUS_SKULL.get());

        helper.basicItemModel(ModItems.APATOSAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.ALBERTOSAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.BRACHIOSAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.CERATOSAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.COMPSOGNATHUS_TISSUE.get());
        helper.basicItemModel(ModItems.DILOPHOSAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.DIPLODOCUS_TISSUE.get());
        helper.basicItemModel(ModItems.GALLIMIMUS_TISSUE.get());
        helper.basicItemModel(ModItems.INDOMINUS_REX_TISSUE.get());
        helper.basicItemModel(ModItems.OURANOSAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.PARASAUROLOPHUS_TISSUE.get());
        helper.basicItemModel(ModItems.SPINOSAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.TRICERATOPS_TISSUE.get());
        helper.basicItemModel(ModItems.TYRANNOSAURUS_REX_TISSUE.get());
        helper.basicItemModel(ModItems.VELOCIRAPTOR_TISSUE.get());
        helper.basicItemModel(ModItems.BARYONYX_TISSUE.get());
        helper.basicItemModel(ModItems.CARNOTAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.CONCAVENATOR_TISSUE.get());
        helper.basicItemModel(ModItems.DEINONYCHUS_TISSUE.get());
        helper.basicItemModel(ModItems.EDMONTOSAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.GIGANOTOSAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.GUANLONG_TISSUE.get());
        helper.basicItemModel(ModItems.HERRERASAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.MAJUNGASAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.PROCOMPSOGNATHUS_TISSUE.get());
        helper.basicItemModel(ModItems.PROTOCERATOPS_TISSUE.get());
        helper.basicItemModel(ModItems.RUGOPS_TISSUE.get());
        helper.basicItemModel(ModItems.SHANTUNGOSAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.STEGOSAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.STYRACOSAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.THERIZINOSAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.DISTORTUS_REX_TISSUE.get());
        helper.basicItemModel(ModItems.ALLOSAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.ALVAREZSAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.ANKYLOSAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.ARAMBOURGIANIA_TISSUE.get());
        helper.basicItemModel(ModItems.CARCHARODONTOSAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.CEARADACTYLUS_TISSUE.get());
        helper.basicItemModel(ModItems.CHASMOSAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.COELOPHYSIS_TISSUE.get());
        helper.basicItemModel(ModItems.COELURUS_TISSUE.get());
        helper.basicItemModel(ModItems.CORYTHOSAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.DIMORPHODON_TISSUE.get());
        helper.basicItemModel(ModItems.DRYOSAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.GEOSTERNBERGIA_TISSUE.get());
        helper.basicItemModel(ModItems.GUIDRACO_TISSUE.get());
        helper.basicItemModel(ModItems.HADROSAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.HYPSILOPHODON_TISSUE.get());
        helper.basicItemModel(ModItems.INDORAPTOR_TISSUE.get());
        helper.basicItemModel(ModItems.INOSTRANCEVIA_TISSUE.get());
        helper.basicItemModel(ModItems.LAMBEOSAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.LUDODACTYLUS_TISSUE.get());
        helper.basicItemModel(ModItems.MAMENCHISAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.METRIACANTHOSAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.MOGANOPTERUS_TISSUE.get());
        helper.basicItemModel(ModItems.NYCTOSAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.ORNITHOLESTES_TISSUE.get());
        helper.basicItemModel(ModItems.ORNITHOMIMUS_TISSUE.get());
        helper.basicItemModel(ModItems.OVIRAPTOR_TISSUE.get());
        helper.basicItemModel(ModItems.PACHYCEPHALOSAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.PROCERATOSAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.PTERANODON_TISSUE.get());
        helper.basicItemModel(ModItems.PTERODAUSTRO_TISSUE.get());
        helper.basicItemModel(ModItems.QUETZALCOATLUS_TISSUE.get());
        helper.basicItemModel(ModItems.RAJASAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.SEGISAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.TAPEJARA_TISSUE.get());
        helper.basicItemModel(ModItems.TITANOSAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.TROODON_TISSUE.get());
        helper.basicItemModel(ModItems.TROPEOGNATHUS_TISSUE.get());
        helper.basicItemModel(ModItems.TUPUXUARA_TISSUE.get());
        helper.basicItemModel(ModItems.UTAHRAPTOR_TISSUE.get());
        helper.basicItemModel(ModItems.ZHENYUANOPTERUS_TISSUE.get());
        helper.basicItemModel(ModItems.ACHILLOBATOR_TISSUE.get());
        helper.basicItemModel(ModItems.SUCHOMIMUS_TISSUE.get());
        helper.basicItemModel(ModItems.CHILESAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.THESCELOSAURUS_TISSUE.get());
        helper.basicItemModel(ModItems.MUSSASAURUS_TISSUE.get());

        helper.basicItemModel(ModItems.APATOSAURUS_DNA.get());
        helper.basicItemModel(ModItems.ALBERTOSAURUS_DNA.get());
        helper.basicItemModel(ModItems.BRACHIOSAURUS_DNA.get());
        helper.basicItemModel(ModItems.CERATOSAURUS_DNA.get());
        helper.basicItemModel(ModItems.COMPSOGNATHUS_DNA.get());
        helper.basicItemModel(ModItems.DILOPHOSAURUS_DNA.get());
        helper.basicItemModel(ModItems.DIPLODOCUS_DNA.get());
        helper.basicItemModel(ModItems.GALLIMIMUS_DNA.get());
        helper.basicItemModel(ModItems.INDOMINUS_REX_DNA.get());
        helper.basicItemModel(ModItems.OURANOSAURUS_DNA.get());
        helper.basicItemModel(ModItems.PARASAUROLOPHUS_DNA.get());
        helper.basicItemModel(ModItems.SPINOSAURUS_DNA.get());
        helper.basicItemModel(ModItems.TRICERATOPS_DNA.get());
        helper.basicItemModel(ModItems.TYRANNOSAURUS_REX_DNA.get());
        helper.basicItemModel(ModItems.VELOCIRAPTOR_DNA.get());
        helper.basicItemModel(ModItems.BARYONYX_DNA.get());
        helper.basicItemModel(ModItems.CARNOTAURUS_DNA.get());
        helper.basicItemModel(ModItems.CONCAVENATOR_DNA.get());
        helper.basicItemModel(ModItems.DEINONYCHUS_DNA.get());
        helper.basicItemModel(ModItems.EDMONTOSAURUS_DNA.get());
        helper.basicItemModel(ModItems.GIGANOTOSAURUS_DNA.get());
        helper.basicItemModel(ModItems.GUANLONG_DNA.get());
        helper.basicItemModel(ModItems.HERRERASAURUS_DNA.get());
        helper.basicItemModel(ModItems.MAJUNGASAURUS_DNA.get());
        helper.basicItemModel(ModItems.PROCOMPSOGNATHUS_DNA.get());
        helper.basicItemModel(ModItems.PROTOCERATOPS_DNA.get());
        helper.basicItemModel(ModItems.RUGOPS_DNA.get());
        helper.basicItemModel(ModItems.SHANTUNGOSAURUS_DNA.get());
        helper.basicItemModel(ModItems.STEGOSAURUS_DNA.get());
        helper.basicItemModel(ModItems.STYRACOSAURUS_DNA.get());
        helper.basicItemModel(ModItems.THERIZINOSAURUS_DNA.get());
        helper.basicItemModel(ModItems.DISTORTUS_REX_DNA.get());
        helper.basicItemModel(ModItems.ALLOSAURUS_DNA.get());
        helper.basicItemModel(ModItems.ALVAREZSAURUS_DNA.get());
        helper.basicItemModel(ModItems.ANKYLOSAURUS_DNA.get());
        helper.basicItemModel(ModItems.ARAMBOURGIANIA_DNA.get());
        helper.basicItemModel(ModItems.CARCHARODONTOSAURUS_DNA.get());
        helper.basicItemModel(ModItems.CEARADACTYLUS_DNA.get());
        helper.basicItemModel(ModItems.CHASMOSAURUS_DNA.get());
        helper.basicItemModel(ModItems.COELOPHYSIS_DNA.get());
        helper.basicItemModel(ModItems.COELURUS_DNA.get());
        helper.basicItemModel(ModItems.CORYTHOSAURUS_DNA.get());
        helper.basicItemModel(ModItems.DIMORPHODON_DNA.get());
        helper.basicItemModel(ModItems.DRYOSAURUS_DNA.get());
        helper.basicItemModel(ModItems.GEOSTERNBERGIA_DNA.get());
        helper.basicItemModel(ModItems.GUIDRACO_DNA.get());
        helper.basicItemModel(ModItems.HADROSAURUS_DNA.get());
        helper.basicItemModel(ModItems.HYPSILOPHODON_DNA.get());
        helper.basicItemModel(ModItems.INDORAPTOR_DNA.get());
        helper.basicItemModel(ModItems.INOSTRANCEVIA_DNA.get());
        helper.basicItemModel(ModItems.LAMBEOSAURUS_DNA.get());
        helper.basicItemModel(ModItems.LUDODACTYLUS_DNA.get());
        helper.basicItemModel(ModItems.MAMENCHISAURUS_DNA.get());
        helper.basicItemModel(ModItems.METRIACANTHOSAURUS_DNA.get());
        helper.basicItemModel(ModItems.MOGANOPTERUS_DNA.get());
        helper.basicItemModel(ModItems.NYCTOSAURUS_DNA.get());
        helper.basicItemModel(ModItems.ORNITHOLESTES_DNA.get());
        helper.basicItemModel(ModItems.ORNITHOMIMUS_DNA.get());
        helper.basicItemModel(ModItems.OVIRAPTOR_DNA.get());
        helper.basicItemModel(ModItems.PACHYCEPHALOSAURUS_DNA.get());
        helper.basicItemModel(ModItems.PROCERATOSAURUS_DNA.get());
        helper.basicItemModel(ModItems.PTERANODON_DNA.get());
        helper.basicItemModel(ModItems.PTERODAUSTRO_DNA.get());
        helper.basicItemModel(ModItems.QUETZALCOATLUS_DNA.get());
        helper.basicItemModel(ModItems.RAJASAURUS_DNA.get());
        helper.basicItemModel(ModItems.SEGISAURUS_DNA.get());
        helper.basicItemModel(ModItems.TAPEJARA_DNA.get());
        helper.basicItemModel(ModItems.TITANOSAURUS_DNA.get());
        helper.basicItemModel(ModItems.TROODON_DNA.get());
        helper.basicItemModel(ModItems.TROPEOGNATHUS_DNA.get());
        helper.basicItemModel(ModItems.TUPUXUARA_DNA.get());
        helper.basicItemModel(ModItems.UTAHRAPTOR_DNA.get());
        helper.basicItemModel(ModItems.ZHENYUANOPTERUS_DNA.get());
        helper.basicItemModel(ModItems.ACHILLOBATOR_DNA.get());
        helper.basicItemModel(ModItems.SUCHOMIMUS_DNA.get());
        helper.basicItemModel(ModItems.CHILESAURUS_DNA.get());
        helper.basicItemModel(ModItems.THESCELOSAURUS_DNA.get());
        helper.basicItemModel(ModItems.MUSSASAURUS_DNA.get());

        helper.basicItemModel(ModItems.APATOSAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.ALBERTOSAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.BRACHIOSAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.CERATOSAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.COMPSOGNATHUS_SYRINGE.get());
        helper.basicItemModel(ModItems.DILOPHOSAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.DIPLODOCUS_SYRINGE.get());
        helper.basicItemModel(ModItems.GALLIMIMUS_SYRINGE.get());
        helper.basicItemModel(ModItems.INDOMINUS_REX_SYRINGE.get());
        helper.basicItemModel(ModItems.OURANOSAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.PARASAUROLOPHUS_SYRINGE.get());
        helper.basicItemModel(ModItems.SPINOSAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.TRICERATOPS_SYRINGE.get());
        helper.basicItemModel(ModItems.TYRANNOSAURUS_REX_SYRINGE.get());
        helper.basicItemModel(ModItems.VELOCIRAPTOR_SYRINGE.get());
        helper.basicItemModel(ModItems.BARYONYX_SYRINGE.get());
        helper.basicItemModel(ModItems.CARNOTAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.CONCAVENATOR_SYRINGE.get());
        helper.basicItemModel(ModItems.DEINONYCHUS_SYRINGE.get());
        helper.basicItemModel(ModItems.EDMONTOSAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.GIGANOTOSAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.GUANLONG_SYRINGE.get());
        helper.basicItemModel(ModItems.HERRERASAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.MAJUNGASAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.PROCOMPSOGNATHUS_SYRINGE.get());
        helper.basicItemModel(ModItems.PROTOCERATOPS_SYRINGE.get());
        helper.basicItemModel(ModItems.RUGOPS_SYRINGE.get());
        helper.basicItemModel(ModItems.SHANTUNGOSAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.STEGOSAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.STYRACOSAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.THERIZINOSAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.DISTORTUS_REX_SYRINGE.get());
        helper.basicItemModel(ModItems.ALLOSAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.ALVAREZSAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.ANKYLOSAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.ARAMBOURGIANIA_SYRINGE.get());
        helper.basicItemModel(ModItems.CARCHARODONTOSAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.CEARADACTYLUS_SYRINGE.get());
        helper.basicItemModel(ModItems.CHASMOSAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.COELOPHYSIS_SYRINGE.get());
        helper.basicItemModel(ModItems.COELURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.CORYTHOSAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.DIMORPHODON_SYRINGE.get());
        helper.basicItemModel(ModItems.DRYOSAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.GEOSTERNBERGIA_SYRINGE.get());
        helper.basicItemModel(ModItems.GUIDRACO_SYRINGE.get());
        helper.basicItemModel(ModItems.HADROSAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.HYPSILOPHODON_SYRINGE.get());
        helper.basicItemModel(ModItems.INDORAPTOR_SYRINGE.get());
        helper.basicItemModel(ModItems.INOSTRANCEVIA_SYRINGE.get());
        helper.basicItemModel(ModItems.LAMBEOSAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.LUDODACTYLUS_SYRINGE.get());
        helper.basicItemModel(ModItems.MAMENCHISAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.METRIACANTHOSAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.MOGANOPTERUS_SYRINGE.get());
        helper.basicItemModel(ModItems.NYCTOSAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.ORNITHOLESTES_SYRINGE.get());
        helper.basicItemModel(ModItems.ORNITHOMIMUS_SYRINGE.get());
        helper.basicItemModel(ModItems.OVIRAPTOR_SYRINGE.get());
        helper.basicItemModel(ModItems.PACHYCEPHALOSAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.PROCERATOSAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.PTERANODON_SYRINGE.get());
        helper.basicItemModel(ModItems.PTERODAUSTRO_SYRINGE.get());
        helper.basicItemModel(ModItems.QUETZALCOATLUS_SYRINGE.get());
        helper.basicItemModel(ModItems.RAJASAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.SEGISAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.TAPEJARA_SYRINGE.get());
        helper.basicItemModel(ModItems.TITANOSAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.TROODON_SYRINGE.get());
        helper.basicItemModel(ModItems.TROPEOGNATHUS_SYRINGE.get());
        helper.basicItemModel(ModItems.TUPUXUARA_SYRINGE.get());
        helper.basicItemModel(ModItems.UTAHRAPTOR_SYRINGE.get());
        helper.basicItemModel(ModItems.ZHENYUANOPTERUS_SYRINGE.get());
        helper.basicItemModel(ModItems.ACHILLOBATOR_SYRINGE.get());
        helper.basicItemModel(ModItems.SUCHOMIMUS_SYRINGE.get());
        helper.basicItemModel(ModItems.CHILESAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.THESCELOSAURUS_SYRINGE.get());
        helper.basicItemModel(ModItems.MUSSASAURUS_SYRINGE.get());

        helper.simpleBlockItemModel(ModBlocks.APATOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.ALBERTOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.BRACHIOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.CERATOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.COMPSOGNATHUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.DILOPHOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.DIPLODOCUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.GALLIMIMUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INDOMINUS_REX_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.OURANOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.PARASAUROLOPHUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.SPINOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.TRICERATOPS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.TYRANNOSAURUS_REX_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.VELOCIRAPTOR_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.BARYONYX_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.CARNOTAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.CONCAVENATOR_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.DEINONYCHUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.EDMONTOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.GIGANOTOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.GUANLONG_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.HERRERASAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.MAJUNGASAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.PROCOMPSOGNATHUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.PROTOCERATOPS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.RUGOPS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.SHANTUNGOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.STEGOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.STYRACOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.THERIZINOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.DISTORTUS_REX_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.ALLOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.ALVAREZSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.ANKYLOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.ARAMBOURGIANIA_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.CARCHARODONTOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.CEARADACTYLUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.CHASMOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.COELOPHYSIS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.COELURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.CORYTHOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.DIMORPHODON_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.DRYOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.GEOSTERNBERGIA_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.GUIDRACO_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.HADROSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.HYPSILOPHODON_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INDORAPTOR_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INOSTRANCEVIA_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.LAMBEOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.LUDODACTYLUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.MAMENCHISAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.METRIACANTHOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.MOGANOPTERUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.NYCTOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.ORNITHOLESTES_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.ORNITHOMIMUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.OVIRAPTOR_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.PACHYCEPHALOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.PROCERATOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.PTERANODON_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.PTERODAUSTRO_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.QUETZALCOATLUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.RAJASAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.SEGISAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.TAPEJARA_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.TITANOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.TROODON_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.TROPEOGNATHUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.TUPUXUARA_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.UTAHRAPTOR_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.ZHENYUANOPTERUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.ACHILLOBATOR_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.SUCHOMIMUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.CHILESAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.THESCELOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.MUSSASAURUS_EGG.get());

        helper.basicItemModel(ModBlocks.LOW_SECURITY_FENCE_POLE.get().asItem());
        helper.basicItemModel(ModBlocks.LOW_SECURITY_FENCE_WIRE.get().asItem());
        helper.basicItemModel(ModBlocks.MEDIUM_SECURITY_FENCE_POLE.get().asItem());
        helper.basicItemModel(ModBlocks.MEDIUM_SECURITY_FENCE_WIRE.get().asItem());

        helper.wallItem(ModBlocks.GYPSUM_BRICK_WALL.get(), ModBlocks.GYPSUM_STONE_BRICKS.get());
        helper.wallItem(ModBlocks.REINFORCED_BRICK_WALL.get(), ModBlocks.REINFORCED_STONE_BRICKS.get());

        helper.simpleBlockItemModel(ModBlocks.INCUBATED_BRACHIOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_CERATOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_DILOPHOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_TYRANNOSAURUS_REX_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_TRICERATOPS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_SPINOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_OURANOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_PARASAUROLOPHUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_INDOMINUS_REX_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_GALLIMIMUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_DIPLODOCUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_COMPSOGNATHUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_VELOCIRAPTOR_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_ALBERTOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_APATOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_BARYONYX_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_CARNOTAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_CONCAVENATOR_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_DEINONYCHUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_EDMONTOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_GIGANOTOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_GUANLONG_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_HERRERASAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_MAJUNGASAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_PROCOMPSOGNATHUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_PROTOCERATOPS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_RUGOPS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_SHANTUNGOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_STEGOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_STYRACOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_THERIZINOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_DISTORTUS_REX_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_ALLOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_ALVAREZSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_ANKYLOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_ARAMBOURGIANIA_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_CARCHARODONTOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_CEARADACTYLUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_CHASMOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_COELOPHYSIS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_COELURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_CORYTHOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_DIMORPHODON_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_DRYOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_GEOSTERNBERGIA_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_GUIDRACO_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_HADROSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_HYPSILOPHODON_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_INDORAPTOR_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_INOSTRANCEVIA_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_LAMBEOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_LUDODACTYLUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_MAMENCHISAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_METRIACANTHOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_MOGANOPTERUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_NYCTOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_ORNITHOLESTES_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_ORNITHOMIMUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_OVIRAPTOR_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_PACHYCEPHALOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_PROCERATOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_PTERANODON_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_PTERODAUSTRO_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_QUETZALCOATLUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_RAJASAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_SEGISAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_TAPEJARA_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_TITANOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_TROODON_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_TROPEOGNATHUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_TUPUXUARA_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_UTAHRAPTOR_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_ZHENYUANOPTERUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_ACHILLOBATOR_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_SUCHOMIMUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_CHILESAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_THESCELOSAURUS_EGG.get());
        helper.simpleBlockItemModel(ModBlocks.INCUBATED_MUSSASAURUS_EGG.get());

		helper.flowerItem(ModBlocks.ROYAL_FERN.get());
        helper.flowerItem(ModBlocks.HORSETAIL_FERN.get());
        helper.flowerItem(ModBlocks.WESTERN_SWORD_FERN.get());
        helper.flowerItem(ModBlocks.ONYCHIOPSIS.get());
    }
}
